import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
def column_chart(strs):
    labels=["combine fuzzy and deep q","deep q learning","fuzzy","random"]
    ax=plt.figure(figsize=(15,10))
    x=[i for i in range(0,129)]
    ax1=ax.add_subplot(2,2,1)
    files=pd.read_csv("C:/Users/vutri/OneDrive/Desktop/15092020/code/result4/"+labels[0]+"/thongso.csv")
    ax1.plot(x,files["server"],label="Server")
    ax1.plot(x,files["bus1"],'-.',label="vehicular fog 1")
    ax1.plot(x,files["bus2"],":",label="vehicular fog 2")
    ax1.plot(x,files["bus3"],"--",label="vehicular fog 3")
    ax1.set_title("Fuzzy-Controller in Deep Q learning")
    ax1.set_xlabel("Time slot")
    ax1.set_ylabel("Number of tasks")
    ax1.set_ylim(0,1300)
    ax2=ax.add_subplot(2,2,2)
    files=pd.read_csv("C:/Users/vutri/OneDrive/Desktop/15092020/code/result3/"+labels[1]+"/thongso.csv")
    ax2.plot(x,files["server"])
    ax2.plot(x,files["bus1"],'-.')
    ax2.plot(x,files["bus2"],":")
    ax2.plot(x,files["bus3"],"--")
    ax2.set_title("Epsilon-Greedy in Deep Q learning")
    ax2.set_xlabel("Time slot")
    ax2.set_ylabel("Number of tasks")
    ax2.set_ylim(0,1300)
    ax3=ax.add_subplot(2,2,3)
    files=pd.read_csv("C:/Users/vutri/OneDrive/Desktop/15092020/code/result4/"+labels[2]+"/thongso.csv")
    ax3.plot(x,files["server"])
    ax3.plot(x,files["bus1"],'-.')
    ax3.plot(x,files["bus2"],":")
    ax3.plot(x,files["bus3"],"--")
    ax3.set_title("Fuzzy Controller")
    ax3.set_xlabel("Time slot")
    ax3.set_ylabel("Number of tasks")
    ax3.set_ylim(0,1300)
    ax4=ax.add_subplot(2,2,4)
    files=pd.read_csv("C:/Users/vutri/OneDrive/Desktop/15092020/code/result4/"+labels[3]+"/thongso.csv")
    ax4.plot(x,files["server"])
    ax4.plot(x,files["bus1"],'-.')
    ax4.plot(x,files["bus2"],":")
    ax4.plot(x,files["bus3"],"--")
    ax4.set_title("Random")
    ax4.set_xlabel("Time slot")
    ax4.set_ylabel("Number of tasks")
    ax4.set_ylim(0,1300)
    ax.legend()
    plt.savefig("thongsoct.png")
column_chart("combine fuzzy and deep q")